apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - image: sundayfagbuaro/k8s-test-img:v1
        name: flask-app
        env:
        - name: MYSQL_HOST
          value: flask-db
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: MYSQL_DB
          value: users_db
        ports:
        - containerPort: 5000
          name: flask-app
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-svc
spec:
  ports:
  - port: 5000
  selector:
    app: flask-db
  type: 
    NodePort
