apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS users_db;


    use users_db

    CREATE TABLE new_users (
        id INT AUTO_INCREMENT,
        f_name VARCHAR(30),
        l_name VARCHAR(30),
        address VARCHAR(30),
        phone VARCHAR(11),
        username VARCHAR(30),
        password VARCHAR(20),
        email VARCHAR(30),
        PRIMARY KEY(id)
    );

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: kubernetes.io/basic-auth
stringData:
  password: password

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   
